website/music/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    #view for album add
    url(r'^album/add/$', views.AlbumCreate.as_view(), name = 'album-add'),
    #view for album update
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'album-update'),
    #view for album delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'album-delete'),
    #url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name = 'favorite'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    def __str__(self):              # __unicode__ on Python 2
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default = False)

    def __str__(self):              # __unicode__ on Python 2
        return self.song_title

website/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'



class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('index')

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container">
  <h2>Add A New Album</h2>
  <form action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
         <button type="submit" class="btn btn-primary">Submit</button>
       </div>
    </div>


  </form>
</div>



{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" >
  <title>{% block title %}Vibeer{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="{% url 'index' %}">First Django Project</a>
       </div>
       <div id="navbar" class="collapse navbar-collapse">
         <ul class="nav navbar-nav">
           <li class="active">
               <a href="{% url 'index' %}">
                   <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Album
               </a>
           </li>
           <li>
               <a href="#">
                   <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
               </a>
           </li>
         </ul>
         <form class="navbar-form navbar-left" role="search" method="get" action="#" >
           <div class="form-group">
             <input type="text" class="form-control" name="q" value="" />
            </div>
            <button type="submit" class="btn btn-default">Search</button>
         </form>
         <ul class="nav navbar-nav navbar-right">
           <li>
               <a href="{% url 'album-add' %}">
                   <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
               </a>
           </li>
           <li>
               <a href="#">
                   <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
               </a>
           </li>
         </ul>
       </div>
     </div>
   </nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Song details{% endblock %}
{% block body %}
  <!--  <img src="{{ album.album_logo }}">
    <h3>{{ album.album_title }}</h3>
    <h4>{{ album.artist }}</h4>


      {% for song in album.song_set.all %}
      <input type="radio" id="{{ forloop.counter }}" name="song" value = "{{ song.id }}" >
      <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
        <img src="http://findicons.com/files/icons/767/wp_woothemes_ultimate/16/star.png" />
        {% endif %}
      </label><br>
      {% endfor %} -->

      <div class="container">
       <div class="row">
            <div class="col-md-3">
              <div class="card">
                <img class="card-img-top" src="{{ album.album_logo }}" alt="Card image cap" />
                <div class="card-block">
                  <h4 class="card-title">{{ album.album_title }}</h4>
                  <p class="card-text">{{ album.artist }}</p>
                </div>
              </div>
            </div>
            <div class="col-md-9">
              <div class="listing-inner">
                <div class="listing-btnsection">
                  <a href="#" class="btn btn-primary">View All</a>
                  <a href="#">Add new Songs</a>
                </div>
              <div class="table-section">
                <div class="table-responsive">
                  <table width="100%" collspacing="0" border="1" cellpadding="0">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Audio File</th>
                        <th>Favorite</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>a</td>
                        <td>a</td>
                        <td>a</td>
                        <td>a</td>
                      </tr>
                    </tbody>

                  </table>
                </div>
              </div>
            </div>
            </div>
        </div>
      </div>
{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
   <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
      </div>
      <label class="control-label col-sm-2">{{ field.label_tag }}</label>
      <div class="col-sm-10">{{ field }}</div>
   </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

  <div class="container">
   <div class="row">
      {% for album in all_albums %}
        <div class="col-md-4">
          <div class="card">
            <img class="card-img-top" src="{{ album.album_logo }}" alt="Card image cap" />
            <div class="card-block">
              <h4 class="card-title">{{ album.album_title }}</h4>
              <p class="card-text">{{ album.artist }}.</p>
              <a href="{% url 'detail' album.id %}" class="btn btn-primary">Detail View</a>
           <!-- This For Delete Album  -->
              <form action="{% url 'album-delete' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                  <span class="glyphicon glyphicon-trash"></span>
                </button>
              </form>
           <!-- End Delete Album Form  -->
              <a href="{% url 'detail' album.id %}" class="btn btn-default"><span class="glyphicon glyphicon-star-empty"></span></a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}